version: '4.3'
services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfront
    ports:
      - "8501:8000"
    volumes:
      - .:/app
    depends_on:
      - backend
    # networks:
    #   #- data_network
    #   - kong_network  
  backend:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "8008:8000" # change port here from 8000 to 8008
    volumes:
      - .:/app
    environment:
        DATABASE_URL: "postgresql://testdb_owner:Gxf49mATunVW@ep-shy-cake-a1jkjuiw.ap-southeast-1.aws.neon.tech/companydata?sslmode=require"
        KAFKA_BROKER_URL: "broker:9092"
    # networks:
    #   #- data_network
    #   - kong_network
  # db:
  #    image: postgres:latest
  #    environment:
  #    POSTGRES_USER: testdb_owner
  #    POSTGRES_PASSWORD: Gxf49mATunVW
  #    POSTGRES_DB: companydata
  #    ports:
  #       - 5432:5432
  # # db:
  #   image: postgres:9.5
  #   environment:
  #     POSTGRES_DB: kong
  #     POSTGRES_USER: kong
  #     POSTGRES_PASSWORD: kong
  #   ports:
  #     - 5432:5432
    # networks:
    #   #- data_network
    # #   - kong_network
    #   healthcheck:
    #   test:
    #     - "CMD"
    #     - "pg_isready"
    #     - "-d"
    #     - "kong"
    #     - "-U"
    #     - "kong"
    #   interval: 30s
    #   timeout: 30s
    #   retries: 3
    # restart: on-failure
    # stdin_open: true
    # tty: true
    # volumes:
    #   - kong_data:/var/lib/postgresql/data
  
  broker:
    image: apache/kafka:3.7.0
    hostname: broker
    container_name: broker
    ports:
      - '19092:19092'
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT'
      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT_HOST://localhost:9092,PLAINTEXT://broker:19092'
      KAFKA_PROCESS_ROLES: 'broker,controller'
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@broker:29093'
      KAFKA_LISTENERS: 'CONTROLLER://:29093,PLAINTEXT_HOST://:9092,PLAINTEXT://:19092'
      KAFKA_INTER_BROKER_LISTENER_NAME: 'PLAINTEXT'
      KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
      CLUSTER_ID: '4L6g3nShT-eMCtK--X86sw'
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_LOG_DIRS: '/tmp/kraft-combined-logs'
 #-----------------------------------------------------------------------------------------------------------
  
  kafka-ui:
    container_name: kafka-ui
    image: provectuslabs/kafka-ui:latest
    ports:
      - 8080:8080
    depends_on:
      - broker
    environment:
      DYNAMIC_CONFIG_ENABLED: 'true'
      KAFKA_CLUSTERS_0_NAME: 'local'
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: 'broker:19092'
    
#================================================================================================
networks:
 default:
  driver: bridge
#================================================================================================